name: Lunes Keep Alive

on:
  schedule:
    - cron: "0 16 * * *" # 北京时间 00:00（UTC+8） 
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Check Node
        run: |
          echo "Checking node..."
          if nc -z node64.lunes.host 3179; then
            echo "Node is ONLINE"
          else
            echo "Node is OFFLINE"
          fi
